"""Generate synthetic historical daily consumption.

Deterministic (fixed seed). Writes:
  - data/historical_consumption.json   (backend training data)
  - frontend/src/data/history.ts       (mirrored series for offline fallback)

Clearly synthetic demonstration data — NOT real hospital data.
"""
import json
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"
FRONT = ROOT / "frontend" / "src" / "data"

SEED = 26
DAYS = 45

# mild per-facility daily trend (%/day): mostly slight growth, one flat, one easing
TRENDS = {"hA": 0.15, "hB": 0.08, "hC": 0.20, "hD": 0.0, "rmc": 0.10, "dh": 0.12, "ch": -0.05}
# day-of-week multipliers (Mon..Sun): mild weekend dip + midweek peak
DOW = np.array([1.0, 1.02, 1.04, 1.03, 1.01, 0.93, 0.90])

def gen_series(base: float, trend_pct: float, rng: np.random.Generator, n: int = DAYS) -> list[int]:
    t = np.arange(n)
    level = base * (1 + (trend_pct / 100.0) * t)
    seasonal = DOW[np.arange(n) % 7]
    noise = rng.normal(1.0, 0.04, n)
    vals = level * seasonal * noise
    # occasional demand variation: 2-3 spike days per series
    for _ in range(int(rng.integers(2, 4))):
        vals[int(rng.integers(0, n))] *= float(rng.uniform(1.15, 1.30))
    return [max(1, int(round(v))) for v in vals]

def main() -> None:
    rng = np.random.default_rng(SEED)
    with open(DATA / "inventory.json", encoding="utf-8") as f:
        inventory = json.load(f)
    series = []
    for inv in inventory:
        fid, mid = inv["facility_id"], inv["medicine_id"]
        trend = TRENDS.get(fid, 0.05) if mid == "m_amox" else 0.05
        series.append({
            "facility_id": fid, "medicine_id": mid,
            "base_daily": inv["daily_consumption"],
            "daily": gen_series(float(inv["daily_consumption"]), trend, rng),
        })
    payload = {
        "meta": {"source": "Synthetic historical demonstration data — NOT real hospital data",
                 "days": DAYS, "seed": SEED, "pairs": len(series)},
        "series": series,
    }
    with open(DATA / "historical_consumption.json", "w", encoding="utf-8") as f:
        json.dump(payload, f)
    compact = {f"{s['facility_id']}|{s['medicine_id']}": s["daily"] for s in series}
    ts = ("// AUTO-GENERATED by backend/generate_history.py — synthetic demo data mirror.\n"
          f"// {DAYS} days per facility|medicine pair. NOT real hospital data.\n"
          "export const HISTORY_DAYS = " + str(DAYS) + ";\n"
          "export const HISTORY: Record<string, number[]> = " + json.dumps(compact) + ";\n")
    FRONT.mkdir(parents=True, exist_ok=True)
    with open(FRONT / "history.ts", "w", encoding="utf-8") as f:
        f.write(ts)
    print(f"wrote {len(series)} series x {DAYS} days")

if __name__ == "__main__":
    main()
